version: '3'

services:
  web:
    build: 
      context: .
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=localhost,127.0.0.1
    restart: unless-stopped
